### ISSUE TITLE
Unable to update documents

### ISSUE THREAD

**Issue by owenj62** [oisinmulvihill/nozama-cloudsearch#18]
The default behaviour for Cloudsearch is to handle an update the same way as an add.
https://docs.aws.amazon.com/cloudsearch/latest/developerguide/preparing-data.html#adding-documents

I'm not sure when this has stopped working but I get an error whenever I try to do this.

E.g.
`curl -X POST -H "Content-Type: application/json" http://localhost:15808/2012-08-22/documents/batch -d '[{"fields": {"name": "bob"}, "type": "add", "id": 123}]'` should add a document with ID 123 and the name "bob"`

Running this command again with the same ID and a new "name" field should update the existing document. 
`curl -X POST -H "Content-Type: application/json" http://localhost:15808/2012-08-22/documents/batch -d '[{"fields": {"name": "Robert"}, "type": "add", "id": 123}]'`

Expected behaviour:
The document with ID 123 should be updated to the name of Robert.

Actual behaviour:
```
2022-02-09 16:10:55,493 DEBUG [nozama.cloudsearch.service.main][MainThread] MongoDB config<{'db_name': 'nozama-cloudsearch', 'port': 27017, 'host': 'mongo'}>
2022-02-09 16:10:55,493 DEBUG [nozama.cloudsearch.service.main][MainThread] ElasticSearch config<{'es_endpoint': 'http://elasticsearch:9200'}>
2022-02-09 16:10:55,494 INFO  [nozama.cloudsearch.data.db.ElasticSearchHelper][MainThread] Using ElasticSearch Endpoint 'http://elasticsearch:9200'
2022-02-09 16:10:55,494 INFO  [nozama.cloudsearch.data.db.ElasticSearchHelper][MainThread] document_uri is 'http://elasticsearch:9200/documents/fields' search_uri is 'http://elasticsearch:9200/documents/fields/_search'
Starting server in PID 1.
2022-02-09 16:11:17,591 DEBUG [nozama.cloudsearch.service.nozamaviews.documents_batch][worker 0] Received from client API Version <2012-08-22>
2022-02-09 16:11:17,596 DEBUG [nozama.cloudsearch.data.document.load][worker 0] to_load: {'fields': {'name': 'bob'}, 'id': '123', 'lang': 'en', 'version': '1644423055', '_id': '123'}
2022-02-09 16:11:17,596 DEBUG [nozama.cloudsearch.data.document.load][worker 0] bulk loading: '1' document(s)
2022-02-09 16:11:17,632 DEBUG [nozama.cloudsearch.data.document.add_to_elasticsearch][worker 0] adding doc <123>
2022-02-09 16:11:17,684 INFO  [elasticsearch][worker 0] GET http://elasticsearch:9200/ [status:200 request:0.052s]
2022-02-09 16:11:18,019 INFO  [elasticsearch][worker 0] PUT http://elasticsearch:9200/documents/_create/123 [status:201 request:0.335s]
2022-02-09 16:11:18,077 INFO  [elasticsearch][worker 0] POST http://elasticsearch:9200/documents/_refresh [status:200 request:0.058s]
2022-02-09 16:11:18,077 DEBUG [nozama.cloudsearch.data.document.add_to_elasticsearch][worker 0] doc <123> add result: {'_index': 'documents', '_type': '_doc', '_id': '123', '_version': 1, 'result': 'created', '_shards': {'total': 2, 'successful': 1, 'failed': 0}, '_seq_no': 0, '_primary_term': 1}
2022-02-09 16:11:18,077 DEBUG [nozama.cloudsearch.service.nozamaviews.documents_batch][worker 0] Document Batch response <{'status': 'ok', 'adds': 1, 'deletes': 0, 'error': '', 'warning': ''}>
2022-02-09 16:11:30,374 DEBUG [nozama.cloudsearch.service.nozamaviews.documents_batch][worker 1] Received from client API Version <2012-08-22>
2022-02-09 16:11:30,375 DEBUG [nozama.cloudsearch.data.document.load][worker 1] to_load: {'fields': {'name': 'robert'}, 'id': '123', 'lang': 'en', 'version': '1644423055', '_id': '123'}
2022-02-09 16:11:30,375 DEBUG [nozama.cloudsearch.data.document.load][worker 1] bulk loading: '1' document(s)
2022-02-09 16:11:30,376 DEBUG [nozama.cloudsearch.data.document.add_to_elasticsearch][worker 1] adding doc <123>
2022-02-09 16:11:30,386 WARNI [elasticsearch][worker 1] PUT http://elasticsearch:9200/documents/_create/123 [status:409 request:0.010s]
2022-02-09 16:11:30,387 ERROR [nozama.cloudsearch.service.restfulhelpers.JSONErrorHandler][worker 1] error: 
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/pyramid/tweens.py", line 13, in _error_handler
    response = request.invoke_exception_view(exc_info)
  File "/usr/local/lib/python3.9/site-packages/pyramid/view.py", line 786, in invoke_exception_view
    raise HTTPNotFound
pyramid.httpexceptions.HTTPNotFound: The resource could not be found.
2022-02-09T16:11:30.388577563Z 
During handling of the above exception, another exception occurred:
2022-02-09T16:11:30.388586543Z 
Traceback (most recent call last):
  File "/app/nozama/cloudsearch/service/restfulhelpers.py", line 196, in __call__
    return self.app(environ, start_response)
  File "/app/nozama/cloudsearch/service/restfulhelpers.py", line 166, in __call__
    return self.application(environ, start_response)
  File "/usr/local/lib/python3.9/site-packages/pyramid/router.py", line 270, in __call__
    response = self.execution_policy(environ, self)
  File "/usr/local/lib/python3.9/site-packages/pyramid/router.py", line 276, in default_execution_policy
    return router.invoke_request(request)
  File "/usr/local/lib/python3.9/site-packages/pyramid/router.py", line 245, in invoke_request
    response = handle_request(request)
  File "/usr/local/lib/python3.9/site-packages/pyramid/tweens.py", line 43, in excview_tween
    response = _error_handler(request, exc)
  File "/usr/local/lib/python3.9/site-packages/pyramid/tweens.py", line 17, in _error_handler
    reraise(*exc_info)
  File "/usr/local/lib/python3.9/site-packages/pyramid/util.py", line 733, in reraise
    raise value
  File "/usr/local/lib/python3.9/site-packages/pyramid/tweens.py", line 41, in excview_tween
    response = handler(request)
  File "/usr/local/lib/python3.9/site-packages/pyramid/router.py", line 143, in handle_request
    response = _call_view(
  File "/usr/local/lib/python3.9/site-packages/pyramid/view.py", line 674, in _call_view
    response = view_callable(context, request)
  File "/usr/local/lib/python3.9/site-packages/pyramid/config/views.py", line 170, in attr_view
    return view(context, request)
  File "/usr/local/lib/python3.9/site-packages/pyramid/config/views.py", line 196, in predicate_wrapper
    return view(context, request)
  File "/usr/local/lib/python3.9/site-packages/pyramid/viewderivers.py", line 427, in rendered_view
    result = view(context, request)
  File "/usr/local/lib/python3.9/site-packages/pyramid/viewderivers.py", line 141, in _requestonly_view
    response = view(request)
  File "/app/nozama/cloudsearch/service/nozamaviews.py", line 86, in documents_batch
    rc = document.load(request.json_body)
  File "/app/nozama/cloudsearch/data/document.py", line 231, in load
    add_to_elasticsearch(doc)
  File "/app/nozama/cloudsearch/data/document.py", line 85, in add_to_elasticsearch
    result = es.conn.create(
  File "/usr/local/lib/python3.9/site-packages/elasticsearch/client/utils.py", line 168, in _wrapped
    return func(*args, params=params, headers=headers, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/elasticsearch/client/__init__.py", line 344, in create
    return self.transport.perform_request(
  File "/usr/local/lib/python3.9/site-packages/elasticsearch/transport.py", line 458, in perform_request
    raise e
  File "/usr/local/lib/python3.9/site-packages/elasticsearch/transport.py", line 419, in perform_request
    status, headers_response, data = connection.perform_request(
  File "/usr/local/lib/python3.9/site-packages/elasticsearch/connection/http_urllib3.py", line 277, in perform_request
    self._raise_error(response.status, raw_data)
  File "/usr/local/lib/python3.9/site-packages/elasticsearch/connection/base.py", line 330, in _raise_error
    raise HTTP_EXCEPTIONS.get(status_code, TransportError)(
elasticsearch.exceptions.ConflictError: ConflictError(409, 'version_conflict_engine_exception', '[123]: version conflict, document already exists (current version [1])')
2022-02-09 16:11:30,388 ERROR [nozama.cloudsearch.service.restfulhelpers.JSONErrorHandler][worker 1] ConflictError: ConflictError(409, 'version_conflict_engine_exception', '[123]: version conflict, document already exists (current version [1])')
----------------------------------------
Exception occurred during processing of request from ('192.168.128.1', 59618)
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/paste/httpserver.py", line 1092, in process_request_in_thread
    self.finish_request(request, client_address)
  File "/usr/local/lib/python3.9/socketserver.py", line 360, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/local/lib/python3.9/socketserver.py", line 747, in __init__
    self.handle()
  File "/usr/local/lib/python3.9/site-packages/paste/httpserver.py", line 460, in handle
    BaseHTTPRequestHandler.handle(self)
  File "/usr/local/lib/python3.9/http/server.py", line 427, in handle
    self.handle_one_request()
  File "/usr/local/lib/python3.9/site-packages/paste/httpserver.py", line 455, in handle_one_request
    self.wsgi_execute()
  File "/usr/local/lib/python3.9/site-packages/paste/httpserver.py", line 308, in wsgi_execute
    self.wsgi_write_chunk(chunk)
  File "/usr/local/lib/python3.9/site-packages/paste/httpserver.py", line 168, in wsgi_write_chunk
    self.wfile.write(chunk)
  File "/usr/local/lib/python3.9/socketserver.py", line 826, in write
    self._sock.sendall(b)
TypeError: a bytes-like object is required, not 'str'
----------------------------------------


```

**Comment by oisinmulvihill** [comment]
Hi @owenj62 thanks for the report. I don't work on this library very often nowadays. I would welcome any pull requests to fix this.
